services:
  web:
    build: .
    ports:
      - 8000:8000
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: newsfeed
      POSTGRES_PASSWORD: newsfeed
      POSTGRES_DB: newsfeed
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
